application:
  ernestotech:
    key-vault:
      endpoint: https://kvernestotech2.vault.azure.net/
      clientId: "<CLIENT-ID-APP>"
      clientSecret: "<CLIENT-SECRET-APP>"
      tenantId: "<TENANT-ID>"
      secrets:
        serviceBusSecret: csServiceBus
        dataBaseSecret: dbServiceBus